server:
  port: 8080

spring:
  application:
    name: 'veragi-banco-abc'

  profiles:
    active: 'local'

db-schema: veragi_abc_bank

veragi:
  veragi-banco-abc:
    url: 'http://localhost:8080/veragi-banco-abc/v1'